### ISSUE TITLE
Getting API errors in HA 0.117.4 - seems to be broken now

### ISSUE THREAD

**Issue by PhilDGeorge1968** [BnMcG/HomeAssistant-RoboVac#15]
I'm getting some additional log file errors for this component now and can't seem to call the scripts to start and stop Eufy
Any ideas anyone - does this need a re-write. I can't get the other Eufy add-on to recognise my 11c vacuum which is annoying.

-VacuumDevice is deprecated, modify RobovacVacuum to extend VacuumEntity
-Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for eufyrobovac doing I/O at custom_components/eufyrobovac/vacuum.py, line 49: local_code = get_local_code(eufy_username, eufy_password, ip_address)
-Updating eufyrobovac vacuum took longer than the scheduled update interval 0:00:20
-Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/robovac/robovac.py", line 324, in _send_packet
    self.s.send(encrypted_packet_data)
OSError: [Errno 9] Bad file descriptor
-[Errno 32] Broken pipe
[Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/robovac/robovac.py", line 324, in _send_packet
    self.s.send(encrypted_packet_data)
BrokenPipeError: [Errno 32] Broken pipe
-Failed to update RoboVac status: unpack requires a buffer of 2 bytes
Failed to update RoboVac status: [Errno 9] Bad file descriptor

**Comment by JkF50** [comment]
I'm getting the same, looks like it needs some modification - That said, I've noted the status is still correctly reported back to HASS

**Comment by RefineryX** [comment]
I'm also getting the same. Did you manage to fix this? Is this still an active project?
